FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /code/integration_test
WORKDIR /code/integration_test
ADD integration_test/requirements.txt /code/integration_test/
ADD . /code/
RUN pip install -r requirements.txt
